Fixing ADC initialization function to work properly on Portenta H7
arduino-libraries/Arduino_AdvancedAnalog pull request #48
Opened 2023-11-28 15:13 UTC by leonardocavagnis

Main changes:
- Fixing bugs in `adc.begin()` function to allow properly working on Portenta H7
- Adding error checking in `adc.begin()` function
- Updating `README.md` according to the Arduino library guideline
- Restyling and updating `docs/readme.md`

The PR is based on the [ArduinoCore-mbed patch](https://github.com/arduino/ArduinoCore-mbed/commit/1e561292d0c8bd20d92ad78b8fa9c96d25a8501d) related to arduino/mbed-os [PR#34](https://github.com/arduino/mbed-os/pull/34).

Please,
@iabdalkader take a look to `adc.begin()` modifies
@karlsoderby check if `docs/readme.md` sounds good for you

2023-11-29 09:04 UTC, karlsoderby reviewed
Hey @leonardocavagnis I've reviewed the documentation part and it looks great. Left some small suggestions :)

2023-11-29 09:04 UTC, karlsoderby commented on docs/readme.md
> +
```suggestion
## Guides

To learn more about using the DAC & ADC on the GIGA R1 WiFi, check out the [GIGA Advanced DAC/ADC Guide](https://docs.arduino.cc/tutorials/giga-r1-wifi/giga-audio).

This includes examples such as audio playback from USB storage, generate sine waves and more.
```

2023-11-29 09:04 UTC, karlsoderby commented on docs/readme.md
> +AdvancedADC adc_d(A5);
@leonardocavagnis should `adc_c` and `adc_d` be -> `adc_a` and `adc_b`?

2023-11-29 09:16 UTC, leonardocavagnis commented on docs/readme.md
> +AdvancedADC adc_d(A5);
No, I chose them to differentiate the two examples 😉

2023-12-05 10:54 UTC, iabdalkader commented
Hi @leonardocavagnis can you please squash all of the docs update commits into one commit ?

2023-12-05 13:44 UTC, iabdalkader commented
@karlsoderby @leonardocavagnis Why are we removing most of the `README.md` file ?

2023-12-05 13:49 UTC, leonardocavagnis commented
> @karlsoderby @leonardocavagnis Why are we removing most of the `README.md` file ?

I removed it according to the Arduino Library guideline. Most of the information has been moved in the` docs/README.md`

2023-12-05 14:00 UTC, iabdalkader requested changes

2023-12-06 11:12 UTC, merged