Jmdodd95682 patch 1
arduino-libraries/Arduino_AdvancedAnalog pull request #55
Opened 2024-02-06 00:59 UTC by jmdodd95682

The begin() function takes about 106us to execute.  If you're trying to start two ADC, this will mean the first ADC will already be capturing for at least 106us when you execute the ADC.begin() on the second one.  

The changes proposed here allow the following sematics:

adc1.ready(uint32_t resolution, uint32_t sample_rate, size_t n_samples, size_t n_buffers);
adc2.ready(uint32_t resolution, uint32_t sample_rate, size_t n_samples, size_t n_buffers);

adc1.start(resolution)
adc2.start(resolution)

This reduces the skew between the two captures to about 4us.

2024-02-06 00:59 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/arduino-libraries/Arduino_AdvancedAnalog?pullRequest=55) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/arduino-libraries/Arduino_AdvancedAnalog?pullRequest=55) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/arduino-libraries/Arduino_AdvancedAnalog?pullRequest=55) it.</sub>

2024-02-06 08:21 UTC, facchinm commented
Hi @jmdodd95682 ,
if `start() ` and then `ready()` is equivalent to `begin()` I'd change the PR to do that in order to avoid code duplication.

2024-02-06 08:22 UTC, facchinm requested changes
I'd change `begin()` to call `start()` and then `ready()` (if equivalent)

2024-02-06 10:17 UTC, leonardocavagnis commented
> I'd change `begin()` to call `start()` and then `ready()` (if equivalent)

My proposal:
- The current `begin()` function has been removed.
- The `ready()` function will be renamed to begin().
- The `start()` function has been added. There is no need to pass `sample_rate` as input; it could become a private object variable initialized by the `begin()` function.

With these changes, you would use `begin()` to configure the ADC and `start()` to initiate the conversion process.

@facchinm @iabdalkader Sounds good for you?
Please, @iabdalkader could you take a look and give a spin?

Thanks

2024-02-06 10:56 UTC, iabdalkader commented
I can take a look at the issue and PR next week. In the meantime @jmdodd95682 please sign the CLA.

2024-02-06 17:10 UTC, jmdodd95682 commented
Signed the CLA.

I agree with not having code duplication.  I didn't want to just remove begin() if there was some other purpose (e.g. ease of use).  

So we just have start() followed by begin() to do ADC capture.  Do you want me to make those changes to my branch?

2024-02-07 02:44 UTC, jmdodd95682 commented
I had another thought. Rather than getting rid of the existing begin() we should just keep it for backward compatibility with people's existing code. Instead, add a new bool flag to begin with a default of false. When this flag is set true, it does all the setup, but does not start. If the flag is false, it does the legacy behavior of doing the setup and start.

To avoid duplicate code, the begin() will call the new start() routine when the flag is false. So, we get full backward compatibility and get the new functionality with no duplicated code.

2024-02-07 09:06 UTC, leonardocavagnis commented
> I had another thought. Rather than getting rid of the existing `begin()` we should just keep it for backward compatibility with people's existing code. Instead, add a new bool flag to begin with a default of false. When this flag is set `true`, it does all the setup, but does not start. If the flag is `false`, it does the legacy behavior of doing the setup and start.
> 
> To avoid duplicate code, the `begin()` will call the new `start()` routine when the flag is false. So, we get full backward compatibility and get the new functionality with no duplicated code.

Your proposal sounds good!
Do the changes and add commits to this branch

2024-02-07 18:12 UTC, jmdodd95682 commented
Made proposed changes.  Tested on my application, works as expected.

2024-02-07 19:49 UTC, iabdalkader requested changes

2024-02-07 19:49 UTC, iabdalkader commented on src/AdvancedADC.cpp
> +
```suggestion

```

2024-02-07 19:49 UTC, iabdalkader commented on src/AdvancedADC.cpp
> +int AdvancedADC::begin(uint32_t resolution, uint32_t sample_rate, size_t n_samples, size_t n_buffers,bool noStart) {
```suggestion
int AdvancedADC::begin(uint32_t resolution, uint32_t sample_rate, size_t n_samples, size_t n_buffers, bool start) {
```

2024-02-07 19:49 UTC, iabdalkader commented on src/AdvancedADC.cpp
> +
```suggestion
int AdvancedADC::start(uint32_t sample_rate) {
```

2024-02-07 19:49 UTC, iabdalkader commented on src/AdvancedADC.cpp
> -    HAL_NVIC_EnableIRQ(descr->dma_irqn);
Please revert NVIC_ disable/enable IRQ around this function.

2024-02-07 19:49 UTC, iabdalkader commented on src/AdvancedADC.h
> +
```suggestion
```

2024-02-07 19:49 UTC, iabdalkader commented on src/AdvancedADC.h
> +            return begin(resolution, sample_rate, n_samples, n_buffers,noStart);
```suggestion
            return begin(resolution, sample_rate, n_samples, n_buffers, start);
```

2024-02-07 19:49 UTC, iabdalkader commented on src/AdvancedADC.h
> +        int begin(uint32_t resolution, uint32_t sample_rate, size_t n_samples, size_t n_buffers, size_t n_pins, pin_size_t *pins, bool noStart=false) {
```suggestion
        int begin(uint32_t resolution, uint32_t sample_rate, size_t n_samples, size_t n_buffers, size_t n_pins, pin_size_t *pins, bool start=true {
```

`start` is just more straightforward than `!noStart`

2024-02-07 19:49 UTC, iabdalkader commented on src/AdvancedADC.cpp
> +
```suggestion
void AdvancedADC::clear() {
    if (descr && descr->pool) {
        descr->pool->flush();
    }
}

```

2024-02-07 19:49 UTC, iabdalkader commented on src/AdvancedADC.cpp
> +    }
```suggestion
    // Start sampling immediately unless start==false.
    if (start) {  
        return start(sample_rate);
    }
```

2024-02-08 09:25 UTC, leonardocavagnis commented on src/AdvancedADC.h
> +        int begin(uint32_t resolution, uint32_t sample_rate, size_t n_samples, size_t n_buffers, size_t n_pins, pin_size_t *pins, bool noStart=false) {
```suggestion
        int begin(uint32_t resolution, uint32_t sample_rate, size_t n_samples, size_t n_buffers, size_t n_pins, pin_size_t *pins, bool start_sampling = true) {
```

2024-02-08 09:27 UTC, leonardocavagnis commented on src/AdvancedADC.cpp
> +int AdvancedADC::begin(uint32_t resolution, uint32_t sample_rate, size_t n_samples, size_t n_buffers, bool start) {
```suggestion
int AdvancedADC::begin(uint32_t resolution, uint32_t sample_rate, size_t n_samples, size_t n_buffers, bool start_sampling) {
```

2024-02-08 09:27 UTC, leonardocavagnis commented on src/AdvancedADC.cpp
> +
```suggestion
```

2024-02-08 09:28 UTC, leonardocavagnis commented on src/AdvancedADC.cpp
> +    }
```suggestion
    sampling_rate = sample_rate;
    // Start sampling immediately unless start_sampling==false.
    if (start_sampling) {  
        return start();
    }
```

2024-02-08 09:29 UTC, leonardocavagnis commented on src/AdvancedADC.cpp
> +int AdvancedADC::start(uint32_t sample_rate) {
```suggestion
int AdvancedADC::start() {
```

2024-02-08 09:29 UTC, leonardocavagnis commented on src/AdvancedADC.cpp
>      hal_dma_enable_dbm(&descr->dma, descr->dmabuf[0]->data(), descr->dmabuf[1]->data());
```suggestion
    HAL_NVIC_DisableIRQ(descr->dma_irqn);
    hal_dma_enable_dbm(&descr->dma, descr->dmabuf[0]->data(), descr->dmabuf[1]->data());
    HAL_NVIC_EnableIRQ(descr->dma_irqn);
```

2024-02-08 09:38 UTC, leonardocavagnis reviewed
@jmdodd95682 
I removed `sample_rate` parameter from `start()` to avoid duplication.

Please, apply these changes and:
- add the private variable `uint32_t sampling_rate;` here: 
https://github.com/arduino-libraries/Arduino_AdvancedAnalog/blob/f7d081c4a56f1a87f8b4a9f027f2efb2b4174b7c/src/AdvancedADC.h#L30-L34
- Modify this line in: `hal_tim_config(&descr->tim, sampling_rate);` https://github.com/jmdodd95682/Arduino_AdvancedAnalog/blob/0d2b69c152cd8925f64205b94c842d4edde0ae24/src/AdvancedADC.cpp#L224

2024-02-14 14:30 UTC, iabdalkader commented
This change is fine on its own, and it probably wouldn't hurt to merge it (after the issues are fixed) but it doesn't really fix the issue, the 2 ADCs will still be out of sync. I think, if we have time and if this is high priority, we should look into supporting "Dual Mode". In dual mode, one ADC controls the other and sampling is triggered simultaneously. I haven't tested it before but it sounds exactly like what's needed here.

2024-02-14 17:17 UTC, jmdodd95682 commented
I agree.  This was a quick fix and gets them with about 4us of each other.  Not great, but okay as a short-term fix. 
I read about the Dual-Mode as well.  Adc1 and Adc2 can be bound together, with Adc1 being the master.   This seems like a longer effort, but probably worth it.  I thought about doing that enhancement, but I don't have enough experience with the HAL code.

The applications where it would be useful is things like:

1) Capturing two analog signals and using one as a capture trigger (e.g. capture scope application)
2) Recording two correlated signals for low-frequency radar or lidar.

2024-03-14 21:35 UTC, per1234 commented
> we should look into supporting "Dual Mode".

This is now tracked at https://github.com/arduino-libraries/Arduino_AdvancedAnalog/issues/59 (thanks @jmdodd95682!).

2024-03-15 16:52 UTC, iabdalkader commented
Superseded by https://github.com/arduino-libraries/Arduino_AdvancedAnalog/pull/60.

2024-03-15 16:52 UTC, closed without merging