docs: Document API changes and new classes.
arduino-libraries/Arduino_AdvancedAnalog pull request #69
Opened 2024-03-28 15:33 UTC by iabdalkader

2024-03-28 16:15 UTC, leonardocavagnis requested changes
Everything looks fine.
just a note: `start()` function doc is missing

2024-04-02 07:18 UTC, iabdalkader commented
> just a note: `start()` function doc is missing

I2S doesn't have a start function, since it doesn't have the `start` arg like ADC. In IN and INOUT modes it starts on begin, in OUT mode it starts after enough buffers are written to the pool, just like DAC.

2024-04-02 07:30 UTC, iabdalkader commented
I see a few issues in the old API docs that should be fixed, will update this again.

2024-04-02 16:39 UTC, leonardocavagnis approved these changes

2024-04-03 08:28 UTC, merged